### ISSUE TITLE
Error applying firbase and pushe co for notification

### ISSUE THREAD

**Issue by jafarpishdadi** [pusheco/pushe-react-native-sample#2]
```

MyFCMService.java:8: error: package co.ronash.pushe does not exist
import co.ronash.pushe.Pushe;
                     ^
F:\i---\android\app\src\main\java\com\--------\MyFCMService.java:14: error: package co.ronash.pushe does not exist
        co.ronash.pushe.Pushe.getFcmHandler(this).onNewToken(s);
                       ^
F:\----\android\app\src\main\java\com\---------\MyFCMService.java:19: error: package co.ronash.pushe does not exist
   

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

import co.ronash.pushe.Pushe;


public class MyFCMService extends FirebaseMessagingService {
    @Override
    public void onNewToken(String s) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onNewToken(s);
        super.onNewToken(s);
    }
    @Override
    public void onDeletedMessages() {
        co.ronash.pushe.Pushe.getFcmHandler(this).onDeletedMessages();
        super.onDeletedMessages();
    }
    @Override
    public void onSendError(String s, Exception e) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onSendError(s, e);
        super.onSendError(s, e);
    }
    @Override
    public void onMessageSent(String s) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onMessageSent(s);
        super.onMessageSent(s);
    }
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (!co.ronash.pushe.Pushe
            .getFcmHandler(this)
            .onMessageReceived(remoteMessage)) {
            // It is for fire base, otherwise the condition will handle the message for Pushe
            super.onMessageReceived(remoteMessage);
        }
    }
}

```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
ممنون که اطلاع دادید این مورد رو

اگر از سرویس **پلاس پوشه** استفاده می‌کنید (که سرویس جدید و جایگزین قدیمی‌هاست) پکیج‌نیم رو به **co.pushe.plus** تغییر بدید و بررسی کنید که مشکل حل میشه یا نه؟

</div>

**Comment by h4m3d66** [comment]
`public class MyFCMService extends FirebaseMessagingService {
                                  ^
  symbol: class FirebaseMessagingService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:23: error: cannot find symbol
    public void onMessageReceived(RemoteMessage remoteMessage) {
                                  ^
  symbol:   class RemoteMessage
  location: class MyFCMService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:2: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:4: error: cannot find symbol
        co.pushe.plus.Pushe.getFcmHandler().onNewToken(s);
                     ^
  symbol:   class Pushe
  location: package co.pushe.plus
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:5: error: cannot find symbol
        super.onNewToken(s);
        ^
  symbol:   variable super
  location: class MyFCMService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:7: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:9: error: cannot find symbol
        co.pushe.plus.Pushe.getFcmHandler().onDeletedMessages();
                     ^
  symbol:   class Pushe
  location: package co.pushe.plus
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:10: error: cannot find symbol
        super.onDeletedMessages();
        ^
  symbol:   variable super
  location: class MyFCMService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:12: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:14: error: cannot find symbol
        co.pushe.plus.Pushe.getFcmHandler().onSendError(s, e);
                     ^
  symbol:   class Pushe
  location: package co.pushe.plus
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:15: error: cannot find symbol
        super.onSendError(s, e);
        ^
  symbol:   variable super
  location: class MyFCMService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:19: error: cannot find symbol
        co.pushe.plus.Pushe.getFcmHandler().onMessageSent(s);
                     ^
  symbol:   class Pushe
  location: package co.pushe.plus
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:20: error: cannot find symbol
        super.onMessageSent(s);
        ^
  symbol:   variable super
  location: class MyFCMService
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:24: error: cannot find symbol
        if (!co.pushe.plus.Pushe
                          ^
  symbol:   class Pushe
  location: package co.pushe.plus
/home/me/Projects/Tapesh/android/app/src/main/java/MyFCMService.java:28: error: cannot find symbol
            super.onMessageReceived(remoteMessage);
            ^
  symbol:   variable super
  location: class MyFCMService
Note: /home/me/Projects/Tapesh/android/app/src/debug/java/com/tapesh/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
17 errors`

**Comment by mahdi-malv** [comment]
@iamhaaamed 
به نظر میاد کلا پکیج شناخته نشده‌ست. پوشه به درستی پلاگینش ایمپورت نشده.
